### ISSUE TITLE
Thêm mới button save trong editfile

### ISSUE THREAD

**Issue by Theodorescsa** [Group-Multi-Projects/EzPDF-FE#6]
-Khi bấm save sẽ gọi đến api html2pdf
-Kết quả mong muốn:
Nhận được file output pdf
![image](https://github.com/user-attachments/assets/9d97b673-4ffd-439d-9fae-09b7abf9b494)
Tham Khảo:
Sau khi người dùng edit xong, lưu toàn bộ mã html đã render + với html được thêm từ phía người dùng vào một file html
sau đó gọi api html2pdf, tham số file là file html trên

**Comment by anluu203** [comment]
done 
![image](https://github.com/user-attachments/assets/d420a3ba-1ad1-4e71-b2da-9fdc0cbd0027)

**Comment by Theodorescsa** [comment]
okey
